name: ApacheInstall
description: This installs Apache on a server and start service on startup
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: ApacheInstall
        action: ExecuteBash
        inputs:
          commands:
            - yum update -y
            - yum install -y httpd.x86_64
            - sudo chkconfig httpd on