aws:
  accountId: "637423642269"
  region: "eu-west-3"
demo:
  dynamodb:
    tableName: "organizations"
    partitionKey: "index"
  sqs: 
    queueName: "organizations"
  lambda:
    name: "LambdaDemo"
  