aws:
  accountId: "637423642269"
  region: "eu-west-3"
demo:
  dynamodb:
    tableName: "demo_employee"
    partitionKey: "LastName"
    sortKey: "FirstName"
    secondaryRegion: "eu-west-1"
  s3: 
    bucketName: "eventnotification-demo-457663"
    inputObjectPrefix : "files"
  lambda: 
    name: "DynamoDB-S3Feeder"
    generate: True