AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Tags:
      DemoName: SAMLambdaDeployment
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
Conditions:
  CreateProdResources:
    Fn::Equals:
    - Ref: Environment
    - prod
Resources:
  LambdaSAMDemo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: LambdaSAMDemo
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: MyApi
      AutoPublishAlias: live
      DeploymentPreference:
        Type:
          Fn::If:
          - CreateProdResources
          - Canary10Percent5Minutes
          - AllAtOnce
        Alarms:
        - Ref: AliasErrorMetricGreaterThanZeroAlarm
        - Ref: LatestVersionErrorMetricGreaterThanZeroAlarm
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.LambdaSAMDemo9829e7ebDepLayer
    Metadata:
      SamResourceId: LambdaSAMDemo
  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda alias error count greater than 0
      AlarmName: LambdaAliasErrorCountGreaterThanZero
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: FunctionName
        Value:
          Ref: LambdaSAMDemo
      - Name: Resource
        Value:
          Fn::Sub: ${LambdaSAMDemo}:live
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Tags:
      - Key: DemoName
        Value: SAMLambdaDeployment
  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmName: LatestVersionErrorGreaterThanZeroAlarm
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${LambdaSAMDemo}:live
      - Name: FunctionName
        Value:
          Ref: LambdaSAMDemo
      - Name: ExecutedVersion
        Value:
          Fn::GetAtt:
          - LambdaSAMDemo
          - Version.Version
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Tags:
      - Key: DemoName
        Value: SAMLambdaDeployment
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api
      StageName: Prod
      Tags:
        DemoName: SAMLambdaDeployment
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: C:\Users\charouk.m\Documents\AWS\aws\DevelopingOnAWS\Module_13\SAM\sam-template\.aws-sam\auto-dependency-layer\adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value:
      Fn::Sub: https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
